- src/App.css
- src/App.js
was failing to lookup inscription pictures that had been transferred in their history
> fix inscription lookup bug

- src/assets/scss/elements/_button.scss
- src/assets/scss/elements/_portfolio.scss
- src/assets/scss/elements/_white-version.scss
- src/components/ordinal-card/index.js
- src/components/product-bid/index.js
- src/components/section-title/index.js
- src/components/ui/client-avatar/index.js
- src/components/user-dropdown/index.js
- src/containers/HeroArea.js
- src/containers/OrdinalsArea.js
- src/hooks/index.js
- src/hooks/use-connect-wallet.js
- src/layouts/header.js
- src/layouts/wrapper.js
- src/pages/_document.js
- src/pages/index.js
Receive address hard to find
Replace heart with send
Get started => Connect 
Hide pub key
> fix: Danny's feedback

- src/containers/OrdinalsArea.js
- Add a newline before address display
- Remove suggestion to mint an astral babe (they are sold out!)
> Spacing in Ordinals Area and remove astral babe mint

- src/assets/scss/elements/_portfolio.scss
- src/components/ordinal-card/index.js
- src/containers/OrdinalsArea.js
Example: 
https://github.com/dannydeezy/nosft/issues/30
> Show Inscription Number

- package-lock.json
- package.json
- src/assets/scss/default/_spacing.scss
- src/assets/scss/elements/_button.scss
- src/containers/OrdinalsArea.js
Fixes #10 , #11 
What was added:
- Input field on gallery page
- Search by any of the properties inscriptionId, key, value, blocktime
- Sort by date
- Sort by value
- Change the marginTop css to 50px as I felt 100px was a bit too much 
- Added library match-sorter to help with the filtering
Watch the demo below
https://user-images.githubusercontent.com/24447702/224550359-f4229249-4e09-404d-8fb2-23e63c20bae1.mov
> Add search and sort functionality to gallery

- src/containers/OrdinalsArea.js
There seemed to be an issue where the utxos were not being fully hydrated with ordinal number and ID
> [hotfix] utxos failed to fully hydrate on first page load

- src/components/ordinal-card/index.js
- src/lib/constants.js
> fix: link to ordinals wallet

- src/containers/OrdinalsArea.js
Cleans up and fixes side effects caused by the promises inside the loop.
> fix: repeated issue

- src/pages/api/inscriptions/[address].js
Example:
https://deploy-preview-87--fabulous-meringue-01474b.netlify.app/api/inscriptions/bc1p2344tp4n8c47jpuekprrxdztt4v0u79ghqwtgn9y9k4u3kwex7nqt866up?limit=100
> chore: pick just necessary data for ordinals

- src/pages/api/inscriptions/[address].js
We are still missing non-inscription utxos but we have an issue open for that https://github.com/dannydeezy/nosft/issues/92
> Hotfix: Populate txid and vout correctly for sends

- src/components/ordinal-filter/index.js
- src/containers/OrdinalsArea.js
- src/containers/helpers.js
- src/lib/constants.js
- src/utils/crypto.js
- src/utils/inscriptions.js
- src/utils/utxos.js
Cleans up a bit the logic, to make it easier to move to nostr-core and have better unit tests later.
> chore: cleanup get utxosfunction

- src/components/modals/buy-modal/index.js
- src/components/modals/sell-modal/index.js
- src/services/nostr-relay.js
- src/utils/psbt.js
This should now enable signing of both listing and purchasing ordinals
> Fix for signing all types of psbts

- src/services/nostr-relay.js
- src/utils/psbt.js
Can now sign and broadcast nostr events when using metamask
> Implement signing of nostr events on metamask

- .husky/pre-commit
- .lintstagedrc.js
- package-lock.json
- package.json
It forces lint check before push the code. So if you get errors it doesn’t perform the commit.
`npm i`
> feat: add husky (pre-commit lint) 

- src/containers/product-details/index.js
> chore: hide actions after logout (Send & Sell)

- package-lock.json
- package.json
- src/components/modals/send-modal/index.js
- src/utils/psbt.js
Integrates the Deezy UTXO Boost endpoint if the value of the output falls below 600 sats
> Lightning Boost

- src/assets/scss/elements/_sign-message.scss
- src/assets/scss/header/_nav.scss
- src/assets/scss/style.scss
- src/components/menu/main-menu/index.js
- src/containers/Sign.js
- src/data/general/menu.json
- src/hooks/use-connect-wallet.js
- src/layouts/header.js
- src/pages/tools/sign.js
- src/utils/bip322.js
Adds new top menu with some options like
- Home
- Inscriptions
- Inscribe
- Tools/Sign
Added a new page for signing with bip322
> feat: sign message w/bip322

- src/containers/NostrLive.js
- src/containers/NostrLiveAll.js
- src/utils/inscriptions.js
Avoid duplicates on marketplace.
> chore: remove duplicates and use the lowest value

- src/containers/NostrLive.js
- src/containers/NostrLiveAll.js
- src/containers/product-details/index.js
- src/pages/inscription/[slug].js
- src/utils/nostr.js
- src/utils/utxos.js
Checks if inscription is spent  or not.
We check that in 3 areas
Main page, nostr live component
Nostr view all page
Inscription detail
> feat: check if inscription is spent

- src/utils/openOrdex.js
- src/utils/psbt.js
> feat: enable RBF signaling

- src/components/card-options/index.js
- src/components/modals/buy-with-lighting/index.js
- src/components/modals/send-modal/index.js
- src/components/product-bid/index.js
Uses recommended fee instead of the hardcoded default one.
> feat: recommended fee rate

- src/containers/product-details/index.js
- src/utils/crypto.js
- src/utils/inscriptions.js
Do not reverse output.
Try catch on get outpoint, to avoid breaking the flow for all the other inscriptions.
> fix: outpoint vout value

- src/lib/constants.config.js
> chore: use deezy relay

- src/components/modals/buy-with-lightning/index.js
> chore: fix label buy with lightning

- src/assets/scss/header/_header.scss
> chore: improve header breakpoint

- package-lock.json
- package.json
Updates with fix: https://github.com/deezy-inc/nosft-core/commit/b1adbc7856b4e0f191846d3bb3fcac109b9bf412
> fix: return value as int

- src/containers/helpers.js
> fix: block time error

- src/assets/scss/elements/_product-details.scss
Reduced paddings on metadata, font size and spacing.
Increased padding in the buttons, and increase the separation with the icons
> feat: improve inscription details

- src/assets/scss/elements/_portfolio.scss
- src/components/product-bid/index.js
Display btc value for inscription for sale.
> feat: display btc value for inscription on sale

- src/pages/collection/[slug].js
Displays collection name nicely on the browser tab.
> feat: use collection name

- src/hooks/use-connect-wallet.js
https://linear.app/deezy/issue/ENG-67/handle-error-oops-it-looks-like-you-havent-set-up-your-nostr-key-yet
You should now see the error as toast instead of inside the console
> Display Wallet Connect Errors in Toast

- src/assets/scss/elements/_banner.scss
- src/assets/scss/elements/_portfolio.scss
- src/components/collection-info/index.js
> fix: force circle for collection icon

- package-lock.json
- package.json
See https://github.com/deezy-inc/nosft-core/pull/45
> Fix pagination logic for unconfirmed and confirmed txs

- package-lock.json
- package.json
- src/assets/scss/elements/_bids.scss
- src/assets/scss/style.scss
- src/components/bids/bid-list.js
- src/components/modals/bid-modal/index.js
- src/components/modals/bids-modal/index.js
- src/components/modals/buy-modal/index.js
- src/containers/CollectionLive.js
- src/containers/product-details/index.js
- src/containers/product-details/loading-button.js
- src/hooks/use-auction.js
- src/hooks/use-bid.js
- src/hooks/use-inscription.js
- src/hooks/use-is-spent.js
- src/pages/inscription/[slug].js
- src/services/nosft.js
Enable Create and Accept Bid Auction. Just the functionality. UX/UI is basic just for demonstration. It should be handle in another PR. 
How to test this PR:
0. You require at least two addresses. Please play attention to your fee rate.
1. Login with any Wallet (Alby, Metamask or Unisat).
2. Pick an inscription click on Bid
3. Create a Bid. 
4. Login with the owner address.
5. Accept the Bid.
https://github.com/deezy-inc/deezy-place/assets/126987350/ecfa2444-4fc2-49c4-861a-36766786f626
Fee 8 sats/vB
> feat: bid auction

- src/assets/scss/elements/_bids.scss
- src/components/bids/bid-list.js
- src/components/modals/bids-modal/index.js
- src/containers/product-details/index.js
- src/containers/product-details/loading-button.js
- src/hooks/use-bid.js
- src/pages/inscription/[slug].js
Please create a Bid and you will see your bid.
https://linear.app/deezy/issue/ENG-137/create-a-view-to-see-other-competing-bids
> feat: Create a view to see other competing bids

- src/components/collection-info/index.js
- src/containers/Collection.js
- src/pages/collection/[slug].js
> chore: improve collection mobile layout

- src/hooks/use-inscription.js
Without takes about 7s
https://recordit.co/njQXIX82YR
Which makes sense, since it is 5 seconds of delay + ~2 loading the inscription
With improvement loading time takes less than 2s which makes sense since that's what it takes to load the inscription
https://recordit.co/00b8clIrGs
> feat: load right away

- package-lock.json
- package.json
- src/components/modals/bid-modal/index.js
- src/components/modals/sell-modal/index.js
- src/hooks/use-auction.js
- src/hooks/use-bid.js
- src/hooks/use-inscription.js
- src/hooks/use-is-spent.js
- src/hooks/use-wallet-state.js
- src/utils/bip322.js
> chore: enable xverse

- src/services/nosft.js
This reverts commit f83da75c953da2ca71b88ea447dae433dbede90a.
> Revert "fix: urls"

- package-lock.json
- package.json
- src/components/modals/send-modal/index.js
https://linear.app/deezy/issue/ENG-183/allow-custom-boost-values
> Allow custom boost value

- src/hooks/use-inscription.js
> hotfix: parse add parseInt(_inscription.value)

- .gitignore
- src/components/modals/buy-modal/index.js
https://linear.app/deezy/issue/ENG-209/buy-button-on-cards-is-broken
> chore: track files

- package-lock.json
- package.json
- src/components/modals/send-bulk-modal/select-rate-step.js
- src/containers/WalletArea.js
- Remove runes from cardinal utxos
- Remove runes if there are inscriptions in the tx.
> feat: improve runes support
